/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bug;

import org.apache.pulsar.client.api.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try(PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build()) {
            Consumer consumer = client.newConsumer()
                    .topic("my-topic")
                    .subscriptionName("my-subscription")
                    .subscribe();

            while (true) {
                // Wait for a message
                Message msg = consumer.receive();

                try {
                    // Do something with the message
                    System.out.println("Message received: " + new String(msg.getData()));

                    // Acknowledge the message so that it can be deleted by the message broker
                    consumer.acknowledge(msg);
                } catch (Exception e) {
                    // Message failed to process, redeliver later
                    consumer.negativeAcknowledge(msg);
                }
            }

        } catch (PulsarClientException e) {
            e.printStackTrace();
        }
    }
}
