/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bug;

import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;

public class Client {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        try {
            PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build();

            Producer<byte[]> producer = client.newProducer().topic("my-topic").create();

            producer.sendAsync("My message".getBytes());

            client.close();
        } catch (PulsarClientException e){
            e.printStackTrace();
        }

        Thread.sleep(1000);
    }
}
